### ISSUE TITLE
Is it compatible with GMK's 6u centered spacebar?

### ISSUE THREAD

**Issue by yzlnew** [rixtox/Topre-to-Cherry-MX-Adapter#2]
Many GMK's core set contains a 6u centered spacebar like [this](https://www.massdrop.com/buy/massdrop-x-zambumon-gmk-nautilus-custom-keycap-set).

**Comment by rixtox** [comment]
Current design is incompatible with any 6u spacebar.
However I do have an on going design for GMK's 6u centered spacebar.
It's been a long run and I've been constantly distracted from this project by other matters.
I'm traveling right now and will finish it up when I get back home in early June.

Sorry for anyone waiting for the update. I will send out some free samples for people waiting on this for months.

**Comment by d-yoshi** [comment]
That is what I really want.
I can't wait!

**Comment by d-yoshi** [comment]
Why was this Issue closed?
Was this released somewhere?

**Comment by yzlnew** [comment]
@d-yoshi It seems this repo is deprecated.

**Comment by rixtox** [comment]
It's been done now.

**Comment by yzlnew** [comment]
Shout out to @rixtox .
Now closed officially. Happy modding HHKB 😊
